"""
Even Fibonacci numbers

Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""
def fib(break_point):
    yield 1
    yield 2
    fibSeq = [1,2]   
    while(True):
        nextFib = sum(fibSeq)
        if nextFib > break_point: break
        fibSeq = [fibSeq[-1], nextFib]
        yield nextFib
        
        
print sum([x for x in fib(4000000) if x%2 == 0])
